### ISSUE TITLE
Feat: implement ranges

### ISSUE THREAD

**Issue by okwasniewski** [callstack/ts-regex#17]
## Describe the feature

Swift offers a way to define ranges: 

```swift
Repeat(count: 4) {
    CharacterClass(
      ("a"..."z"),
      ("0"..."9")
    )
  }
  ```
  
This compiles to `[a-z0-9]{4}`
  
For us, the API could look like: 

```js
buildRegex(
   repeat({count: 4}, 
       range({start: "a", end: "z"}, {start: 0, end: 9})
    )
) // [a-z0-9]{4}
```

**Comment by mdjastrzebski** [comment]
Since there are always two elements, how about dropping the named params:
```
buildRegex(
   repeat({count: 4}, 
       range(["a", "z"])
       range(["a", "z"], ["0", "9"])
    )
) // [a-z0-9]{4}
```
@okwasniewski wdyt?

**Comment by okwasniewski** [comment]
Looks good! Let's go with that

**Comment by jaworek** [comment]
Are we planning to support such weird ranges?
<img width="844" alt="image" src="https://github.com/callstack/ts-regex/assets/22678765/1dedf122-0a18-4543-886e-bb77564d39a5">


https://regexone.com/lesson/character_ranges
